name: Build, Lint & Test

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]
  # trigger on merge group as well (merge queue)
  merge_group:
    types: [checks_requested]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

 # To use Remote Caching, uncomment the next lines and follow the steps below.
env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ secrets.TURBO_TEAM }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest-16

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 25

      - name: Install
        uses: ./.github/composite-actions/install

      - run: yarn build

        # We use week in the turbo cache key to keep the cache from infinitely growing
      - id: get-week
        run: echo "WEEK=$(date +%U)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        timeout-minutes: 5
        id: cache-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

  lint:
    name: Lint Packages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true

      - uses: actions/cache@v3
        timeout-minutes: 5
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - run: yarn lint

  test:
    name: Unit Tests
    runs-on: ubuntu-latest-16
    needs: build
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true

      - uses: actions/cache@v3
        timeout-minutes: 5
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - run: yarn test
  
  e2e:
    name: E2E Tests
    runs-on: ubuntu-latest-16
    needs: build
    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true

      - uses: actions/cache@v3
        timeout-minutes: 5
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - name: Install Playwright
        run: npx playwright install --with-deps

      - name: Run e2e tests
        run: yarn e2e
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"

  size:
    name: Size Comparison
    runs-on: ubuntu-latest-8
    needs: build
    timeout-minutes: 30

    steps:
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          check-latest: true

      - uses: actions/cache@v3
        timeout-minutes: 5
        id: restore-build
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}
          
      - uses: preactjs/compressed-size-action@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          strip-hash: "\\-(\\w{8})(?:\\.esm|\\.cjs)"
          minimum-change-threshold: 100
          # exclude source maps, node modules and any test related files
          exclude: "{**/*.map,**/node_modules/**,**/test/**}"
