# On the Version Packages branch created by github-actions[bot]
# Run `pnpm typedoc` to generate the JSON files
# Commit the generated JSON files to the Version Packages branch

name: Commit Typedoc JSON files

on:
  push:
    branches:
      - Version Packages

jobs:
  typedoc:
    if: github.actor == 'github-actions[bot]'
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Typedoc
        run: pnpm typedoc

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "typedoc: update JSON files [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
